# Generated by Django 5.0 on 2023-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_poop_acount_poop_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='poop_account',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
