# Generated by Django 5.0 on 2023-12-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_poop_account_total_poops'),
    ]

    operations = [
        migrations.AddField(
            model_name='poop_account',
            name='poops_count',
            field=models.IntegerField(default=0),
        ),
    ]
