# Generated by Django 5.0.6 on 2024-05-25 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_poop_account_poops_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poop_account',
            name='fiends',
            field=models.ManyToManyField(blank=True, to='app1.poop_account'),
        ),
        migrations.CreateModel(
            name='group_poop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=35)),
                ('players_joined', models.PositiveIntegerField(default=1)),
                ('owner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poop_account',
            name='joined_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.group_poop'),
        ),
    ]
