# Generated by Django 5.0.6 on 2024-05-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_poop_account_fiends_group_poop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poop_account',
            old_name='fiends',
            new_name='friends',
        ),
    ]
