# Generated by Django 5.0.6 on 2024-05-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_fiends_poop_account_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poop_account',
            name='profile_img',
            field=models.ImageField(blank=True, default='./used_media/default.jpg', upload_to='./images'),
        ),
    ]
