# Generated by Django 5.0.6 on 2024-05-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_request', to='app1.poop_account'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_request', to='app1.poop_account'),
        ),
    ]
