# Generated by Django 5.0.6 on 2024-06-07 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_profile_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app1.poop_account'),
        ),
        migrations.AlterField(
            model_name='profile_comment',
            name='recipent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipent_user', to='app1.poop_account'),
        ),
    ]
