# Generated by Django 5.0.6 on 2024-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_profile_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_comment',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
