# Generated by Django 5.0.6 on 2024-06-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_profile_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poop_account',
            name='joined_group',
        ),
        migrations.DeleteModel(
            name='group_poop',
        ),
    ]
