# Generated by Django 5.0.6 on 2024-06-14 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_poop_account_joined_group_delete_group_poop'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_poop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('members', models.ManyToManyField(blank=True, max_length=16, related_name='members', to='app1.poop_account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_group', to='app1.poop_account')),
            ],
        ),
    ]
