# Generated by Django 5.0.6 on 2024-06-14 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_group_poop'),
    ]

    operations = [
        migrations.AddField(
            model_name='poop_account',
            name='joined_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app1.group_poop'),
        ),
    ]
