# Generated by Django 5.0.6 on 2024-06-20 02:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_group_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification', to='app1.poop_account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_notification', to='app1.poop_account')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Notification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.notification')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_notification', to='app1.group_poop')),
            ],
            bases=('app1.notification',),
        ),
    ]
