# Generated by Django 5.0.7 on 2024-07-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_group_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poop_account',
            name='joined_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.group_poop'),
        ),
    ]
