# Generated by Django 5.0.6 on 2024-06-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_notification_group_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_request',
        ),
    ]
