# Generated by Django 5.0.6 on 2024-06-20 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_delete_group_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='date',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='id',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='sender',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='notification_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.notification'),
            preserve_default=False,
        ),
    ]
