# Generated by Django 5.0.6 on 2024-07-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_poop_account_joined_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poop_account',
            old_name='poops_count',
            new_name='global_poops',
        ),
    ]
