# Generated by Django 5.0.7 on 2024-08-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_poop_account_joined_group'),
        ('app1', '0025_group_comment'),
    ]

    operations = [
    ]
