# Generated by Django 5.0.6 on 2024-08-23 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_merge_20240821_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_comment',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='poops',
            name='owner_shit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.poop_account'),
        ),
    ]
