# Generated by Django 5.0.6 on 2024-08-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_group_comment_message_alter_poops_owner_shit'),
    ]

    operations = [
        migrations.AddField(
            model_name='poop_account',
            name='group_poops',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poop_account',
            name='global_poops',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
