# Generated by Django 5.0.6 on 2024-08-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_poop_account_group_poops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_comment',
            name='type_message',
            field=models.CharField(default='chat', max_length=30),
        ),
    ]
