# Generated by Django 5.0.6 on 2024-08-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_group_comment_type_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_comment',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='authro_gc', to='app1.poop_account'),
        ),
    ]
