# Generated by Django 5.2 on 2025-04-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_group_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_poop',
            name='members',
        ),
    ]
