# Generated by Django 5.2 on 2025-04-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_remove_group_poop_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poop_account',
            name='joined_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poop_accounts', to='app1.group_poop'),
        ),
    ]
